#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# ///
"""Generate the simulator's firmware version header from the current checkout.

This deliberately runs on every build. Git's dirty state can change without
touching HEAD or the index, so there is no complete static dependency list for
it. The file is only replaced when its contents change, keeping incremental
compilation cheap.
"""

import argparse
import json
import subprocess
from datetime import datetime
from pathlib import Path


def git(repo: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        # Source archives and minimal build containers may not provide git.
        # Version metadata is useful, but it must not be a build dependency.
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    commit = git(args.repo, "rev-parse", "--short", "HEAD") or "unknown"
    branch = git(args.repo, "rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    dirty = bool(git(args.repo, "status", "--porcelain", "--untracked-files=no"))
    suffix = "-dirty" if dirty else ""

    text = "\n".join(
        [
            "/* Generated by simulator/tools/gen_version_header.py. */",
            f"#define GIT_COMMIT {json.dumps(commit)}",
            f"#define GIT_BRANCH {json.dumps(branch)}",
            f'#define BUILD_DATE "{datetime.now().strftime("%d-%m-%Y")}"',
            '#define VERSION "simulator"',
            f"#define BUILD_DIRTY {int(dirty)}",
            f"#define BUILD_DIRTY_SUFFIX {json.dumps(suffix)}",
            '#define FIRMWARE_ORIGIN "BUSY"',
            '#define GIT_ORIGIN ""',
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text() != text:
        temporary = args.output.with_suffix(args.output.suffix + ".tmp")
        temporary.write_text(text)
        temporary.replace(args.output)
        print(f"version: {commit}{suffix} ({branch})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
