#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# ///
"""Generate the applications.c that fbt would generate, for the host build.

lib/firmware_applications_*/applications.h declares FLIPPER_APPS,
FLIPPER_SETTINGS_APPS and friends; fbt fills them in from the application.fam
manifests via a jinja template. Apps read those lists at runtime -- the
settings menu enumerates FLIPPER_SETTINGS_APPS and launches whatever is in it
-- so the simulator needs the same table, listing exactly the apps it links.

The .fam files are Python, so they are executed here with the same App() shim
fbt uses, rather than pattern-matched. Anything in a manifest this does not
model is ignored on purpose: the simulator only needs the entry point, name,
appid, stack size and type.
"""

import argparse
import sys
from pathlib import Path

# Mirrors lib/firmware_applications_u5/template/applications.c.tmpl.
APP_TYPE_TO_ARRAY = {
    "SERVICE": "FLIPPER_SERVICES",
    "SYSTEM": "FLIPPER_SYSTEM_APPS",
    "APP": "FLIPPER_APPS",
    "DEBUG": "FLIPPER_DEBUG_APPS",
    "SETTINGS": "FLIPPER_SETTINGS_APPS",
}

# Emitted empty when nothing declares them, so the symbols still resolve.
ALL_ARRAYS = list(APP_TYPE_TO_ARRAY.values())


class AppType:
    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return f"FlipperAppType.{self.name}"


class AppTypes:
    def __getattr__(self, name):
        return AppType(name)


def read_manifest(path: Path) -> dict:
    apps = []

    def App(**kwargs):
        apps.append(kwargs)

    def ExtFile(**kwargs):
        pass

    namespace = {
        "App": App,
        "ExtFile": ExtFile,
        "Lib": ExtFile,
        "FlipperAppType": AppTypes(),
    }

    exec(compile(path.read_text(), str(path), "exec"), namespace)

    if len(apps) != 1:
        raise ValueError(f"{path}: expected exactly one App(), found {len(apps)}")

    return apps[0]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--autorun", default="")
    parser.add_argument(
        "manifest",
        type=Path,
        nargs="+",
        help="application.fam files for the apps linked into the simulator",
    )
    args = parser.parse_args()

    by_array: dict[str, list[dict]] = {name: [] for name in ALL_ARRAYS}

    for path in args.manifest:
        if not path.exists():
            print(f"{path}: no such manifest", file=sys.stderr)
            return 1

        try:
            app = read_manifest(path)
        except Exception as error:  # noqa: BLE001 - reported, not swallowed
            print(f"{path}: could not read manifest: {error}", file=sys.stderr)
            return 1

        apptype = app.get("apptype")
        if apptype is None:
            print(f"{path}: manifest has no apptype", file=sys.stderr)
            return 1

        array = APP_TYPE_TO_ARRAY.get(apptype.name)
        if array is None:
            print(
                f"{path}: apptype {apptype.name} is not one the simulator "
                "links; drop it from the manifest list in CMakeLists.txt",
                file=sys.stderr,
            )
            return 1

        for key in ("entry_point", "name", "appid"):
            if not app.get(key):
                print(f"{path}: manifest has no {key}", file=sys.stderr)
                return 1

        by_array[array].append(app)

    lines = [
        "/* Generated by simulator/tools/gen_app_registry.py -- do not edit. */",
        '#include "applications.h"',
        "",
        f'const char* FLIPPER_AUTORUN_APP_NAME = "{args.autorun}";',
        "",
    ]

    for array in ALL_ARRAYS:
        apps = sorted(by_array[array], key=lambda app: app.get("order", 0))

        for app in apps:
            lines.append(f'extern int32_t {app["entry_point"]}(void* context);')
        if apps:
            lines.append("")

        lines.append(f"const FlipperInternalApplication {array}[] = {{")
        for app in apps:
            lines.extend(
                [
                    "    {",
                    f'        .app = {app["entry_point"]},',
                    f'        .name = "{app["name"]}",',
                    f'        .appid = "{app["appid"]}",',
                    f'        .stack_size = {app.get("stack_size", 4096)},',
                    "        .flags = FlipperInternalApplicationFlagDefault,",
                    "    },",
                ]
            )
        lines.append("};")
        lines.append(
            f"const size_t {array}_COUNT = "
            f"sizeof({array}) / sizeof({array}[0]);"
        )
        lines.append("")

    # Declared by applications.h; nothing in the simulator provides them, but
    # an empty array with a zero count is what the firmware would have when no
    # app of that kind is built in.
    lines.extend(
        [
            "const FlipperInternalOnStartHook FLIPPER_ON_SYSTEM_START[] = {};",
            "const size_t FLIPPER_ON_SYSTEM_START_COUNT = 0;",
            "",
            "const FlipperInternalCommandApplication FLIPPER_CLI_COMMANDS[] = {};",
            "const size_t FLIPPER_CLI_COMMANDS_COUNT = 0;",
            "",
            "const FlipperExternalApplication FLIPPER_EXTERNAL_APPS[] = {};",
            "const size_t FLIPPER_EXTERNAL_APPS_COUNT = 0;",
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))

    total = sum(len(apps) for apps in by_array.values())
    print(f"app registry: {total} apps -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
