#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow"]
# ///
"""Turn the device renders into raw frames the simulator can load without a decoder.

simulator/assets/{front,back}.png are photographic backdrops the window draws
the two virtual displays onto. They cannot be decoded at load time: the only
PNG decoder linked into the simulator is LVGL's lodepng, which allocates
through lv_malloc, and sim_window_init() runs before the scheduler starts.
Stripping them to headerless RGB24 here means the window reads straight into a
locked SDL texture -- no decoder, no allocation, no dependency on furi's heap.

Emits, into <out>:

    front.rgb24, back.rgb24        row-major RGB, no header, no padding
    sim_background_generated.h     paths and dimensions for src/sim_background.c

The dimensions land in the header so the rectangles in sim_background.c, which
are measured in the source images' pixels, can be static_asserted against the
images they were measured from.
"""

import argparse
import sys
from pathlib import Path

from PIL import Image

SIDES = ("front", "back")


def convert(source: Path, target: Path) -> tuple[int, int]:
    with Image.open(source) as image:
        rgb = image.convert("RGB")
        size = rgb.size

        if target.exists() and target.stat().st_mtime >= source.stat().st_mtime:
            return size

        target.write_bytes(rgb.tobytes())

    return size


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets", type=Path, required=True, help="PNG source directory")
    parser.add_argument("--out", type=Path, required=True, help="Generated output directory")
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* Generated by simulator/tools/gen_panel_backgrounds.py. */",
        "#pragma once",
        "",
    ]

    for side in SIDES:
        source = args.assets / f"{side}.png"
        if not source.is_file():
            print(f"missing background: {source}", file=sys.stderr)
            return 1

        target = args.out / f"{side}.rgb24"
        width, height = convert(source, target)

        lines += [
            f'#define SIM_BACKGROUND_{side.upper()}_PATH "{target}"',
            f"#define SIM_BACKGROUND_{side.upper()}_WIDTH ({width})",
            f"#define SIM_BACKGROUND_{side.upper()}_HEIGHT ({height})",
            "",
        ]

    header = args.out / "sim_background_generated.h"
    text = "\n".join(lines)

    # Rewriting an identical header would rebuild everything that includes it.
    if not header.exists() or header.read_text() != text:
        header.write_text(text)

    print(f"backgrounds: {', '.join(SIDES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
